services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    command: ["start-dev"]
    ports:
      - "9091:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"